version: '1'
services:
  redis:
    image: redis
    container_name: cache
    ports:
        - '6379:6379'
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: passroot

